service: agenda

provider:
  name: aws
  runtime: nodejs14.x

functions:
  createAgendamento:
    handler: handler.createAgendamento
    events:
      - http:
          path: agendamentos
          method: post

  getAgendamentos:
    handler: handler.getAgendamentos
    events:
      - http:
          path: agendamentos
          method: get
plugins:
  - serverless-offline
